name: HTGEconomyAPI
version: '${project.version}'
main: pl.htgmc.htgeconomyapi.HTGEconomyAPI
api-version: '1.21'
depend:
  - PlaceholderAPI
  - LuckPerms
  - Vault
commands:
  coins:
    description: Sprawdź lub zarządzaj monetami gracza
    usage: /coins [gracz] [dodaj|usun|ustaw|kara] [ilość] [powod - kara]
    permission: htg.coins.admin
  dynamics:
    description: Pokazuje statystyki dynamicznej ekonomii
    usage: /dynamics
    permission: htg.dynamics.admin
  transfer:
    description: Przewalutuj środki lub przelej HTG do innego gracza
    usage: /transfer <tohtg|tovault|toplayer> <kwota> [nick]
    permission: htg.transfer