name: HTGEconomyAPI
version: '${project.version}'
main: pl.htgmc.htgeconomyapi.HTGEconomyAPI
api-version: '1.21'
depend:
  - PlaceholderAPI
  - LuckPerms
  - Vault
commands:
  coins:
    description: Sprawdź swoje saldo lub zarządzaj saldem innych
    usage: /coins lub /coins manager <gracz> [dodaj|usun|ustaw|kara|info] <kwota> <powód>
  dynamics:
    description: Pokazuje statystyki dynamicznej ekonomii
    usage: /dynamics
    permission: htgcoins.dynamics
  transfer:
    description: Przewalutuj środki lub przelej HTG do innego gracza
    usage: /transfer <tohtg|tovault|toplayer> <kwota> [nick]
  bank:
    description: Otwiera GUI banku gracza
    usage: /bank

permissions:
  htgcoins.admin:
    description: Dostęp do zarządzania monetami innych graczy
    default: op

  htgcoins.dynamics:
    description: Dostęp do sprawdzania dynamicznej ekonomi
    default: op